In [1]:
from ucimlrepo import fetch_ucirepo 
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
from random import choices, sample

In [2]:
iris = fetch_ucirepo(id=53)

In [3]:
X = iris.data.features 
y = iris.data.targets

In [4]:
X

     sepal length  sepal width  petal length  petal width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [5]:
scaler = MinMaxScaler((-1, 1))

In [6]:
scaler.fit(X)

MinMaxScaler(feature_range=(-1, 1))

In [7]:
X_scaled = scaler.transform(X)

In [8]:
X_scaled = pd.DataFrame(X_scaled, index=X.index, columns=X.columns)

In [9]:
X_scaled

     sepal length  sepal width  petal length  petal width
0       -0.555556     0.250000     -0.864407    -0.916667
1       -0.666667    -0.166667     -0.864407    -0.916667
2       -0.777778     0.000000     -0.898305    -0.916667
3       -0.833333    -0.083333     -0.830508    -0.916667
4       -0.611111     0.333333     -0.864407    -0.916667
..            ...          ...           ...          ...
145      0.333333    -0.166667      0.423729     0.833333
146      0.111111    -0.583333      0.355932     0.500000
147      0.222222    -0.166667      0.423729     0.583333
148      0.055556     0.166667      0.491525     0.833333
149     -0.111111    -0.166667      0.389831     0.416667

[150 rows x 4 columns]

In [10]:
y

              class
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 1 columns]

In [11]:
y_linsep = pd.Series([1 if x == "Iris-setosa" else 0 for x in y['class']])

In [12]:
train_indices = sample(range(150), k=int(0.8 * 150))

In [13]:
X_train = X_scaled.iloc[sorted(train_indices)]

In [14]:
X_train

     sepal length  sepal width  petal length  petal width
1       -0.666667    -0.166667     -0.864407    -0.916667
2       -0.777778     0.000000     -0.898305    -0.916667
3       -0.833333    -0.083333     -0.830508    -0.916667
4       -0.611111     0.333333     -0.864407    -0.916667
7       -0.611111     0.166667     -0.830508    -0.916667
..            ...          ...           ...          ...
145      0.333333    -0.166667      0.423729     0.833333
146      0.111111    -0.583333      0.355932     0.500000
147      0.222222    -0.166667      0.423729     0.583333
148      0.055556     0.166667      0.491525     0.833333
149     -0.111111    -0.166667      0.389831     0.416667

[120 rows x 4 columns]

In [15]:
X_test = X_scaled.iloc[~X_scaled.index.isin(X_train.index)]

In [16]:
len(X_test)

30

In [17]:
y_train = y_linsep[X_train.index]

In [18]:
y_test = y_linsep[X_test.index]

In [19]:
y_train

1      1
2      1
3      1
4      1
7      1
      ..
145    0
146    0
147    0
148    0
149    0
Length: 120, dtype: int64

In [30]:
from perceptron import Perceptron
p = Perceptron(4)

In [31]:
losses = p.train(X_train, y_train, epochs=3)

-1.3535933248337213
-3.3898210009361236
-5.801204670433535
-7.191948192983391
-9.645412379966018
-15.178451711720022
-16.186859183287222
-13.330050977303868
-18.812274692706755
-25.43384529696104
-31.786611460602778
-10.587105365557361
-18.91957890904327
-27.088071021806442
-25.161145241852868
-29.584241708922875
-28.55452964584005
-42.041917635118224
-34.99358225463537
-41.64753233062937
-50.49318883338457
-43.0092279287601
-47.61285594974215
-57.807121929786675
-61.00596818265271
-40.80595129306594
-34.921605433281705
-70.37746755342503
-69.87613155755646
-56.4767651492366
-78.11899297715385
-91.10841847709177
-67.99944412699406
-111.44368637506818
-94.29171205522701
-61.750069208274596
-54.84412615892683
-96.34027885459406
-99.909767961813
-70.44040626257663
-93.26013833104454
21.446570696617137
34.03210575391559
-40.772789456971445
11.025378415864369
-13.227355193499115
-67.76850369866742
9.561986296868307
-30.610469593741467
-73.54141144142545
-0.5727062218673771
-40.66879786403438
17.670211940931203
-2.4318117355082336
-14.452369607728183
-36.56394456666234
21.84992293073609
-10.758794087821837
1.286128123012185
-4.878117785055251
1.2902291030957223
11.425638246488836
13.809136702820313
26.831512666010244
-35.87047361480869
-39.458250048896346
-20.128101808915822
6.037344163233194
-4.890774503424457
16.248763508692665
-10.460769588487286
-24.428126641685207
-20.427012177629194
4.325340035102146
-19.317941681088868
-48.70346220827616
-15.734408060507738
-9.930421215024621
-1.794123812194826
-43.297632027288245
-13.004634388709903
51.94770677469926
9.117073452084405
43.26591455054405
21.008291877864878
33.75423393150315
49.42740216103117
-13.663756115879231
17.555857522997805
53.54472546463893
23.017607593934102
13.48939520382978
24.418681849260942
13.988499127128811
22.362125487404374
14.607651200380467
29.496861610359456
-3.22175108991223
22.68341838935578
4.376796663857676
4.928371949995324
15.489113787440317
3.9951824528794186
4.637411341968036
7.237219786331412
6.843856415121429
6.80272601260456
4.31026384752376
1.3619284347663339
1.4214623142252194
1.3999895891642438
0.47806303804754324
-1.329870704013567
0.7787763339940128
-3.380587067284398
-2.458244788105037
-0.008235273930011888
-2.196653873138434
-3.393365702504509
-0.4715681692159274
7.56156386790859
7.5106377892881095
7.973644252038648
5.506401845627501
6.052919229236606
9.103204118874354
7.451550608525675
4.138662902969498
6.471804780364264
7.99818249092775
9.384898003805658
0.7652158168184977
2.6333075134463586
4.4789879759367395
3.632477951707777
4.113220982662062
3.605912951328624
5.513347866123956
4.320158325866088
5.294618523903387
5.943914757436925
4.230540624779417
4.48392149525372
6.033112139564823
6.058955681392943
2.8525451840237923
1.6767672658224602
5.517857499431754
4.924510530269439
3.129604461463581
5.380794472586194
6.486096514912252
3.8902195066469805
7.6429245419200385
5.961370889964207
3.2412290682129297
2.6104805237313053
5.11399868243153
5.232808753381214
2.7077099197718013
4.055122737060791
-0.9721875665119128
-2.005166357589685
3.50865122297372
-0.698975367388825
2.2119214936463765
9.30088035484538
-1.2879259686959241
5.905194549384126
14.943787816582816
0.6122214650773083
10.077040364383933
-4.792019781007518
1.7001539485345794
5.083918700443501
12.535350920673594
-6.645618993423164
4.110802723031472
0.4954577616393019
2.8893031474090716
-0.43152432588473166
-5.357986950571114
-6.420863203547291
-12.863163557622029
19.375399747732754
22.44186731842451
12.258854545391063
-2.070866951822623
4.723551609766394
-10.293280714990654
8.22488063888202
19.18457483241116
17.37709876483218
-2.5898518608529364
17.009582443151047
43.88846875598249
15.699596687732535
10.434032663714406
2.265482400923821
45.11295203708878
14.91579431003201
-54.4609394325354
-7.838335348580406
-49.97908533575284
-23.626251151335577
-41.2039323862595
-65.10129735917263
23.081548054879303
-23.181565053286178
-80.97483117901542
-35.939375894384895
-20.703468494038418
-42.50723540389077
-23.368817364410695
-43.69820066788919
-29.608472591370223
-66.77082009832803
12.279809816967056
-58.297303172979184
-8.06496910203273
-12.958273530662638
-52.079367858619435
-12.7877377822822
-17.28297555051312
-32.3069260381392
-41.16904923807062
-50.353058959741226
-34.920027889091116
-9.784743588386148
-3.221941672198895
-54.339239001062616
-14.472459909917482
-47.460642236162045
-8.463318062141777
-62.60939412300095
-44.36686574000171
-11.272801281506082
-32.862792243164925
-47.88586686212218
-15.659823867543388
81.65973728607972
80.99634366436212
83.47575923682722
63.86178530387384
68.18030776927611
93.45929065535196
80.60938690843824
52.88485630172502
70.83049655824186
86.10362264506009
98.25626491842846
23.537402341497838
44.33863201667846
62.07963120483399
53.08949736995033
58.86016997235497
53.134907692872886
75.19180320997393
59.15563168652847
67.8156763939552
77.82229275465022
61.86344766541113
65.5301189801836
77.98152350005601
78.81569033827262
48.50938104221059
38.75357563422184
80.60938690828354
76.51859045340656
58.390634509327896
80.60938690828354
91.80249944983484
64.91213568138986
105.990732911252
86.47903692972365
54.04835270584011
46.45341621394977
80.87098077062895
81.8189680313288
54.712420723460944
71.8469790839172
-16.242505440725914
-26.738356583772713
34.41849793834215
-8.703979440028451
12.799188571753502
61.2133353413102
-8.42912946528326
30.194057100430655
72.47055913612944
1.3654361553705159
42.295280689912026
-18.74471498965308
4.3222928577144835
17.335539966757054
42.68185866015139
-23.777097586679798
13.23993496521086
0.019716355001460073
7.5598372458028
-1.4486997816858622
-15.282798236287004
-18.63297775214262
-37.33985928351588
54.19208259174431
60.610968585268616
31.807896887474016
-6.863883637808076
10.490414557711759
-25.895439454717973
19.440176604043756
44.821694498303614
39.15053948934604
-6.493777465995971
37.84754122088359
95.94990726741914
33.031103852850904
21.448573569619537
4.42021255977448
91.51310500523448
29.30427101869622
-108.32377311338665
-16.576113750333242
-98.91533670831674
-47.49039128858697
-82.04677740173547
-128.7211085236012
43.89891664475877
-45.81089029032888
-157.18438556545834
-70.01758276074251
-40.87658583162626
-82.82662627544474
-46.36053392998057
-85.25240643953379
-58.04948099903008
-130.12219323856107
22.722048864234274
-111.63594679049879
-16.453658649327576
-25.3062884542156
-99.8742347149728
-24.961268879926823
-33.590405356017726
-62.505870089360386
-78.84390966108299
-96.47020196418384
-67.49462220567503
-19.314188155660375
-7.288724773387024
-104.26911322594601
-28.211552817435745
-90.71532711930185
-17.1893173986537
-119.83061547209385
-84.90023968229661
-22.196974483546537
-63.11536636161134
-91.9310412321775
-30.71238954544119

In [32]:
losses

[-0.02841676252683941, -0.23618542580616406, -0.23724880767490839]

In [39]:
train_pred = p.test(X_train)

156.09152423629246
154.8115517923689
159.31495436816232
122.47698507575937
130.5754037990331
178.1718592714774
154.07609396302428
101.83585322990385
135.42383012803754
164.48955638985464
187.44573193926686
46.391030425436746
85.7298364292016
119.1131722590069
102.04049429823225
112.99847133964155
102.08590462115478
143.99395743584222
113.29393305381507
129.51377027700056
148.74226119592612
118.7227381828733
125.72697747002864
148.90149194133193
150.52648813846656
93.50623117590239
75.22555335652606
154.07609396302428
146.55390232368939
112.43510866453947
154.07609396302428
175.1076598850134
124.49241534902761
201.94916308911897
165.03922121139402
103.6159284563293
89.17160548296249
154.5119383620804
156.2507549816983
105.24507636957891
137.5796430861884
-31.04039717370052
-50.93237333664872
64.77830289416457
-16.2827629164825
22.938660179037786
108.95598908948612
-14.74858736519301
51.850305902409545
121.74360339635847
1.9842170493310451
67.73283357426028
-29.275018291683217
6.301826617319268
26.120242473746337
63.248279058990065
-34.870768368023576
19.151867372065897
-0.27171847774035385
10.350536733533403
-2.020081234805957
-20.831575815198494
-25.461663222311852
-51.02734569860884
73.66174148582043
80.6205704500532
41.372585092133484
-9.041336646913008
13.120272896669345
-32.46075230250677
24.159524446476123
54.709864220545214
46.78437409624
-7.725500017514526
44.4367844785975
110.58098528662077
37.29216250655948
23.76909037034251
4.798365044544147
98.02457431047623
30.818739980420425
-112.10378276489112
-17.189317409224195
-102.34965386596842
-49.165162519060004
-84.91310409145957
-133.18590921676326
45.35986725131876
-46.60521763121282
-159.85946898274128
-71.21378508488507
-41.58469614796586
-84.24190464556062
-47.16758181546942
-86.71102888756266
-59.04780818487414
-132.34593288801076
23.088589001368145
-111.63722438732056
-16.453859579879563
-25.30658419302106
-99.8753794170059
-24.96156043981001
-33.59079592409995
-62.50659336358673
-78.84481198586226
-96.47130648429129
-67.49540237747384
-19.31441638886069
-7.288822173732402
-104.26911328643104
-28.211552834079278
-90.7153271716997
-17.189317409224195
-119.83061547255434
-84.90023968262281
-22.19697448363445
-63.11536636161139
-91.93104123217756
-30.712389545441212

In [37]:
test_pred = p.test(X_test)

124.10198127289401
77.84975662781896
141.19350729419185
79.0063625118116
77.64511555949062
118.6277658209132
106.96089321255866
127.16618065935803
105.0592833617737
-50.44696689855502
-41.59424228541355
-4.6613006310505085
39.04384353501409
47.410163219216386
-2.3008466045712836
67.67372539777506
-40.1738871566073
29.624437975381507
23.814500693265074
-97.04753356823008
-6.730444659471255
-183.82771601514844
-123.50790461927748
-102.83090858794714
-174.75848441568735
-136.7226506324842
-60.672804382008756
-102.80334783470222
-94.7828853484369
-112.16804114833681

In [35]:
p.weights

array([-61.36601651, -60.41063204, -58.11558854, -59.86570817])

In [36]:
from sklearn.metrics import accuracy_score

In [38]:
accuracy_score(y_test, test_pred)

0.8333333333333334

In [40]:
accuracy_score(y_train, train_pred)

0.7666666666666667

In [42]:
len(y_test)

30

In [43]:
sum(y_train)

41