In [1]:
import pandas as pd

In [2]:
review_df = pd.read_csv("IMDb_Reviews.csv")

In [3]:
review_df

                                                  review  sentiment
0      My family and I normally do not watch local mo...          1
1      Believe it or not, this was at one time the wo...          0
2      After some internet surfing, I found the "Home...          0
3      One of the most unheralded great works of anim...          1
4      It was the Sixties, and anyone with long hair ...          0
...                                                  ...        ...
49995  the people who came up with this are SICK AND ...          0
49996  The script is so so laughable... this in turn,...          0
49997  "So there's this bride, you see, and she gets ...          0
49998  Your mind will not be satisfied by this nobud...          0
49999  The chaser's war on everything is a weekly sho...          1

[50000 rows x 2 columns]

In [10]:
import spacy

In [8]:
from gensim.models.doc2vec import Doc2Vec, TaggedDocument

In [12]:
nlp = spacy.load("en_core_web_sm")

In [5]:
sentences = [review_df.iloc[0]['review'], review_df.iloc[1]['review']]

In [6]:
sentences

['My family and I normally do not watch local movies for the simple reason that they are poorly made, they lack the depth, and just not worth our time.<br /><br />The trailer of "Nasaan ka man" caught my attention, my daughter in law\'s and daughter\'s so we took time out to watch it this afternoon. The movie exceeded our expectations. The cinematography was very good, the story beautiful and the acting awesome. Jericho Rosales was really very good, so\'s Claudine Barretto. The fact that I despised Diether Ocampo proves he was effective at his role. I have never been this touched, moved and affected by a local movie before. Imagine a cynic like me dabbing my eyes at the end of the movie? Congratulations to Star Cinema!! Way to go, Jericho and Claudine!!',
 'Believe it or not, this was at one time the worst movie I had ever seen. Since that time, I have seen many more movies that are worse (how is it possible??) Therefore, to be fair, I had to give this movie a 2 out of 10. But it was a tough call.']

In [14]:
output = [nlp(x) for x in sentences]

In [23]:
for token in enumerate(output[0]):
    print(token)

(0, My)
(1, family)
(2, and)
(3, I)
(4, normally)
(5, do)
(6, not)
(7, watch)
(8, local)
(9, movies)
(10, for)
(11, the)
(12, simple)
(13, reason)
(14, that)
(15, they)
(16, are)
(17, poorly)
(18, made)
(19, ,)
(20, they)
(21, lack)
(22, the)
(23, depth)
(24, ,)
(25, and)
(26, just)
(27, not)
(28, worth)
(29, our)
(30, time.<br)
(31, /><br)
(32, />The)
(33, trailer)
(34, of)
(35, ")
(36, Nasaan)
(37, ka)
(38, man)
(39, ")
(40, caught)
(41, my)
(42, attention)
(43, ,)
(44, my)
(45, daughter)
(46, in)
(47, law)
(48, 's)
(49, and)
(50, daughter)
(51, 's)
(52, so)
(53, we)
(54, took)
(55, time)
(56, out)
(57, to)
(58, watch)
(59, it)
(60, this)
(61, afternoon)
(62, .)
(63, The)
(64, movie)
(65, exceeded)
(66, our)
(67, expectations)
(68, .)
(69, The)
(70, cinematography)
(71, was)
(72, very)
(73, good)
(74, ,)
(75, the)
(76, story)
(77, beautiful)
(78, and)
(79, the)
(80, acting)
(81, awesome)
(82, .)
(83, Jericho)
(84, Rosales)
(85, was)
(86, really)
(87, very)
(88, good)
(89, ,)
(90, so)
(91, 's)
(92, Claudine)
(93, Barretto)
(94, .)
(95, The)
(96, fact)
(97, that)
(98, I)
(99, despised)
(100, Diether)
(101, Ocampo)
(102, proves)
(103, he)
(104, was)
(105, effective)
(106, at)
(107, his)
(108, role)
(109, .)
(110, I)
(111, have)
(112, never)
(113, been)
(114, this)
(115, touched)
(116, ,)
(117, moved)
(118, and)
(119, affected)
(120, by)
(121, a)
(122, local)
(123, movie)
(124, before)
(125, .)
(126, Imagine)
(127, a)
(128, cynic)
(129, like)
(130, me)
(131, dabbing)
(132, my)
(133, eyes)
(134, at)
(135, the)
(136, end)
(137, of)
(138, the)
(139, movie)
(140, ?)
(141, Congratulations)
(142, to)
(143, Star)
(144, Cinema)
(145, !)
(146, !)
(147, Way)
(148, to)
(149, go)
(150, ,)
(151, Jericho)
(152, and)
(153, Claudine)
(154, !)
(155, !)

In [24]:
def build_tagged_documents(documents, tagger):
    for i, document in enumerate(documents):
        processed = tagger(document)
        lemmas = [x.lemma_ for x in processed]
        yield TaggedDocument(lemmas, [i])

In [30]:
tagged = build_tagged_documents(sentences, nlp)

In [26]:
tagged

In [27]:
next(tagged)

TaggedDocument(words=['my', 'family', 'and', 'I', 'normally', 'do', 'not', 'watch', 'local', 'movie', 'for', 'the', 'simple', 'reason', 'that', 'they', 'be', 'poorly', 'make', ',', 'they', 'lack', 'the', 'depth', ',', 'and', 'just', 'not', 'worth', 'our', 'time.<br', '/><br', '/>The', 'trailer', 'of', '"', 'Nasaan', 'ka', 'man', '"', 'catch', 'my', 'attention', ',', 'my', 'daughter', 'in', 'law', "'s", 'and', 'daughter', "'s", 'so', 'we', 'take', 'time', 'out', 'to', 'watch', 'it', 'this', 'afternoon', '.', 'the', 'movie', 'exceed', 'our', 'expectation', '.', 'the', 'cinematography', 'be', 'very', 'good', ',', 'the', 'story', 'beautiful', 'and', 'the', 'act', 'awesome', '.', 'Jericho', 'Rosales', 'be', 'really', 'very', 'good', ',', 'so', "'s", 'Claudine', 'Barretto', '.', 'the', 'fact', 'that', 'I', 'despise', 'Diether', 'Ocampo', 'prove', 'he', 'be', 'effective', 'at', 'his', 'role', '.', 'I', 'have', 'never', 'be', 'this', 'touch', ',', 'move', 'and', 'affect', 'by', 'a', 'local', 'movie', 'before', '.', 'imagine', 'a', 'cynic', 'like', 'I', 'dab', 'my', 'eye', 'at', 'the', 'end', 'of', 'the', 'movie', '?', 'congratulation', 'to', 'Star', 'Cinema', '!', '!', 'way', 'to', 'go', ',', 'Jericho', 'and', 'Claudine', '!', '!'], tags=[0])

In [28]:
next(tagged)

TaggedDocument(words=['believe', 'it', 'or', 'not', ',', 'this', 'be', 'at', 'one', 'time', 'the', 'bad', 'movie', 'I', 'have', 'ever', 'see', '.', 'since', 'that', 'time', ',', 'I', 'have', 'see', 'many', 'more', 'movie', 'that', 'be', 'bad', '(', 'how', 'be', 'it', 'possible', '?', '?', ')', 'therefore', ',', 'to', 'be', 'fair', ',', 'I', 'have', 'to', 'give', 'this', 'movie', 'a', '2', 'out', 'of', '10', '.', 'but', 'it', 'be', 'a', 'tough', 'call', '.'], tags=[1])

In [29]:
next(tagged)

StopIteration:

In [31]:
for x in tagged:
    print(x)

TaggedDocument<['my', 'family', 'and', 'I', 'normally', 'do', 'not', 'watch', 'local', 'movie', 'for', 'the', 'simple', 'reason', 'that', 'they', 'be', 'poorly', 'make', ',', 'they', 'lack', 'the', 'depth', ',', 'and', 'just', 'not', 'worth', 'our', 'time.<br', '/><br', '/>The', 'trailer', 'of', '"', 'Nasaan', 'ka', 'man', '"', 'catch', 'my', 'attention', ',', 'my', 'daughter', 'in', 'law', "'s", 'and', 'daughter', "'s", 'so', 'we', 'take', 'time', 'out', 'to', 'watch', 'it', 'this', 'afternoon', '.', 'the', 'movie', 'exceed', 'our', 'expectation', '.', 'the', 'cinematography', 'be', 'very', 'good', ',', 'the', 'story', 'beautiful', 'and', 'the', 'act', 'awesome', '.', 'Jericho', 'Rosales', 'be', 'really', 'very', 'good', ',', 'so', "'s", 'Claudine', 'Barretto', '.', 'the', 'fact', 'that', 'I', 'despise', 'Diether', 'Ocampo', 'prove', 'he', 'be', 'effective', 'at', 'his', 'role', '.', 'I', 'have', 'never', 'be', 'this', 'touch', ',', 'move', 'and', 'affect', 'by', 'a', 'local', 'movie', 'before', '.', 'imagine', 'a', 'cynic', 'like', 'I', 'dab', 'my', 'eye', 'at', 'the', 'end', 'of', 'the', 'movie', '?', 'congratulation', 'to', 'Star', 'Cinema', '!', '!', 'way', 'to', 'go', ',', 'Jericho', 'and', 'Claudine', '!', '!'], [0]>
TaggedDocument<['believe', 'it', 'or', 'not', ',', 'this', 'be', 'at', 'one', 'time', 'the', 'bad', 'movie', 'I', 'have', 'ever', 'see', '.', 'since', 'that', 'time', ',', 'I', 'have', 'see', 'many', 'more', 'movie', 'that', 'be', 'bad', '(', 'how', 'be', 'it', 'possible', '?', '?', ')', 'therefore', ',', 'to', 'be', 'fair', ',', 'I', 'have', 'to', 'give', 'this', 'movie', 'a', '2', 'out', 'of', '10', '.', 'but', 'it', 'be', 'a', 'tough', 'call', '.'], [1]>

In [33]:
d2vmodel = Doc2Vec(list(build_tagged_documents(sentences, nlp)))

In [36]:
len(d2vmodel.dv[0])

100

In [44]:
import tqdm

all_reviews_tagged = []
for i, doc in tqdm.tqdm(enumerate(build_tagged_documents(list(review_df[0:1000]['review']), nlp))):
    all_reviews_tagged.append(doc)    
#all_reviews_tagged = list(build_tagged_documents(list(review_df['review']), nlp))

1000it [00:48, 20.46it/s]

In [51]:
reviews_d2vmodel = Doc2Vec(all_reviews_tagged)

In [53]:
short_review_df = review_df[0:1000].copy()

In [57]:
reviews_d2vmodel.dv[999]

array([-0.00908835, -0.07047428,  0.06109371, -0.0911529 ,  0.15559947,
       -0.26363453,  0.530304  ,  0.1489148 , -0.4274569 ,  0.18807459,
       -0.34051135,  0.1806071 ,  0.03588738,  0.23293236, -0.3018901 ,
       -0.03281015,  0.02725541, -0.00399299,  0.17116964, -0.01066342,
        0.10121536,  0.10649001,  0.14329354, -0.01197915, -0.34057575,
        0.05177706, -0.16332276, -0.19800644,  0.14390694, -0.16879989,
        0.43087804,  0.27549082,  0.00890878,  0.0973706 , -0.19262463,
        0.47653976, -0.00384357, -0.26696748, -0.07557742, -0.26309916,
        0.31798473,  0.0023189 , -0.31587723, -0.20495455,  0.14095101,
       -0.08004294, -0.12672888, -0.07757963, -0.02637123, -0.12105721,
        0.00256046,  0.02064771,  0.07779089, -0.1167016 ,  0.26681784,
       -0.01220858,  0.16183034,  0.10054033, -0.21748768,  0.08480395,
        0.2440678 ,  0.25215036, -0.25475532,  0.10526682,  0.00143617,
        0.25812358,  0.32180417,  0.17783748,  0.01217025, -0.01922693,
       -0.0313457 , -0.04007921,  0.24582534, -0.13000159,  0.40022075,
        0.07482424,  0.0106154 ,  0.02584132,  0.2562485 ,  0.2885776 ,
        0.04706357, -0.20085458,  0.04563957,  0.44320148, -0.49266416,
       -0.23623456,  0.26012397, -0.25328514,  0.2674154 ,  0.33626062,
       -0.0325286 , -0.01044051, -0.39539564, -0.3613901 ,  0.5096389 ,
        0.12845987,  0.10610381, -0.38514364,  0.47438312,  0.22607388],
      dtype=float32)

In [58]:
review_vectors = [reviews_d2vmodel[x] for x in range(1000)]

In [59]:
short_review_df['vectors'] = review_vectors

In [60]:
short_review_df

,review,sentiment,vectors
0,My family and I normally do not watch local mo...,1,"[-0.0203901, 0.3527077, 0.061519954, 0.0989064..."
1,"Believe it or not, this was at one time the wo...",0,"[-0.91547966, 0.19455665, 0.29183742, -0.34344..."
2,"After some internet surfing, I found the ""Home...",0,"[-0.7197685, 0.8309013, -0.6049588, -0.3233575..."
3,One of the most unheralded great works of anim...,1,"[-0.90065825, 0.60194665, 0.03857616, -0.71919..."
4,"It was the Sixties, and anyone with long hair ...",0,"[-0.35005936, -0.18564168, 0.07280252, -0.0253..."
...,...,...,...
995,I debated as to whether or not I should tick t...,0,"[-0.029101927, -0.16694906, 0.08788262, -0.236..."
996,This movie is amazing. You will NEVER laugh ha...,1,"[-0.17669584, -0.14326213, 0.04519971, -0.1445..."
997,I had never heard of this film before a couple...,1,"[-0.3383694, -0.1280499, 0.2163621, -0.2717652..."
998,"As the above suggests, I was ultimately unimpr...",0,"[-0.06808091, -0.09145717, 0.07894746, -0.0795..."
999,The Bill was essentially a cultural fountain f...,1,"[-0.111408554, -0.21079908, 0.07794363, -0.053..."

In [61]:
import pickle

In [62]:
with open("short_review_df.pkl", "wb") as outputfile:
    pickle.dump(short_review_df, outputfile)